import type { Lesson, CodeLine } from './types';
const lines = (items: [string,string][]): CodeLine[] => items.map(([id,text])=>({id,text}));
export const lessons: Lesson[] = [
  {
    id:'maximum-average',version:1,number:643,slug:'maximum-average-subarray-i',title:'Maximum Average Subarray I',shortTitle:'The best view',pattern:'Fixed-size window',difficulty:'Easy',inputKind:'numbers',parameter:'Window k',
    objective:'Reuse a window’s sum to find the highest average.',defaults:{raw:'1, 12, -5, -6, 50, 3',parameter:'4'},presets:[{label:'All negative',input:{raw:'-5, -2, -8',parameter:'2'}},{label:'Single value',input:{raw:'5',parameter:'1'}}],inputHint:'1–16 integers from −10,000 to 10,000. k must fit the array.',prerequisites:'Start here. Familiarity with arrays and averages helps.',
    story:{title:'A camera with a fixed frame.',paragraphs:['Imagine a row of scenes, each with a score. Your camera captures exactly k neighboring scenes. Find the view with the highest average score.','When the camera moves one place, most of the view stays. Subtract the departing score, add the arriving score, and reuse the rest.'],mapping:'Frame = a contiguous subarray. Width = k. Score = window sum ÷ k.',invariant:'Compare only windows of exactly k values. Since k is constant, the greatest sum has the greatest average.',baseline:'Summing each window from scratch repeats work: O(nk). Reusing the sum takes O(n). Start best from the first full window, even when it is negative.'},complexity:'O(n) time · O(1) extra space',
    code:lines([['def','def findMaxAverage(nums, k):'],['init','    total = 0'],['loop-first','    for i in range(k):'],['first','        total += nums[i]'],['benchmark','    best = total'],['loop','    for right in range(k, len(nums)):'],['remove','        total -= nums[right - k]'],['add','        total += nums[right]'],['save','        best = max(best, total)'],['done','    return best / k']]),
    practices:[{prompt:'nums = [4, -2, 6, 1, -3], k = 2. What is the maximum average?',answer:3.5,question:'Why can each slide take constant time?',options:['Sort the array.','Remove the outgoing value and add the incoming value.','Ignore negative values.'],correct:1,hint:'Consider the four adjacent pairs.',explanation:'[6, 1] has sum 7, so its average is 3.5. Only the two boundary values change.'},{prompt:'nums = [-8, -2, -4], k = 2. What is the maximum average?',answer:-3,question:'How should best be initialized?',options:['To zero.','To the first complete window’s sum.','To the largest individual value.'],correct:1,hint:'The two sums are −10 and −6.',explanation:'[-2, -4] averages −3. Starting best at zero would invent an unavailable window.'}]
  },
  {
    id:'maximum-vowels',version:1,number:1456,slug:'maximum-number-of-vowels-in-a-substring-of-given-length',title:'Maximum Number of Vowels in a Substring of Given Length',shortTitle:'Tune into vowels',pattern:'Fixed-size window',difficulty:'Medium',inputKind:'text',parameter:'Window k',defaults:{raw:'abciiidef',parameter:'3'},presets:[{label:'No vowels',input:{raw:'rhythm',parameter:'3'}},{label:'All vowels',input:{raw:'aeiou',parameter:'2'}}],inputHint:'1–16 lowercase English letters. Vowels: a, e, i, o, u.',prerequisites:'Recommended: The best view.',
    objective:'Track a property of a window instead of its numeric sum.',story:{title:'Tune a radio to the clearest signal.',paragraphs:['A radio scans k neighboring letters at a time. Vowels are signal; other letters are silence. Find the stretch carrying the most signal.','Each vowel contributes 1 and each consonant contributes 0. Moving the frame removes one contribution and adds another.'],mapping:'Radio span = k letters. Vowel = 1 unit of signal. Consonant = 0.',invariant:'The count equals the number of vowels inside the current frame. Compare only full frames.',baseline:'Checking all k letters in every frame costs O(nk). Maintain the count as the frame moves for O(n) time.'},complexity:'O(n) time · O(1) extra space',
    code:lines([['def','def maxVowels(s, k):'],['vowels','    vowels = set("aeiou")'],['init','    count = 0'],['loop-first','    for i in range(k):'],['first','        count += int(s[i] in vowels)'],['benchmark','    best = count'],['loop','    for right in range(k, len(s)):'],['remove','        count -= int(s[right - k] in vowels)'],['add','        count += int(s[right] in vowels)'],['save','        best = max(best, count)'],['done','    return best']]),
    practices:[{prompt:'s = "aeibcd", k = 3. What is the maximum vowel count?',answer:3,question:'What does a consonant contribute?',options:['1','0','It is removed from the string.'],correct:1,hint:'The first frame already contains three vowels.',explanation:'"aei" contains 3 vowels. Consonants contribute 0 but still occupy a position.'},{prompt:'s = "bcdf", k = 2. What is the maximum vowel count?',answer:0,question:'Are windows without vowels valid?',options:['No, skip the whole input.','Yes, their vowel count is zero.','Only if k is 1.'],correct:1,hint:'All three windows contain only consonants.',explanation:'The maximum is 0. Window validity depends on length, not on containing a vowel.'}]
  },
  {
    id:'minimum-size',version:1,number:209,slug:'minimum-size-subarray-sum',title:'Minimum Size Subarray Sum',shortTitle:'Pack just enough',pattern:'Variable-size window',difficulty:'Medium',inputKind:'numbers',parameter:'Target',defaults:{raw:'2, 3, 1, 2, 4, 3',parameter:'7'},presets:[{label:'No solution',input:{raw:'1, 1, 1',parameter:'8'}},{label:'One item fits',input:{raw:'1, 8, 2',parameter:'7'}}],inputHint:'1–16 positive integers up to 10,000. Target: 1–1,000,000,000.',prerequisites:'Recommended: either fixed-size window lesson.',objective:'Expand to reach a target, then shrink to find the shortest valid window.',
    story:{title:'Pack a bag with just enough supplies.',paragraphs:['Supplies arrive in a line. You need at least a target amount, using the shortest uninterrupted group of packages.','Add packages from the right until the bag holds enough. Record its length, then remove from the left while it still holds enough. Every package has a positive amount.'],mapping:'Bag = current contiguous window. Supplies = sum. A valid bag has sum ≥ target.',invariant:'With positive values, expansion increases the sum and shrinking decreases it. Save every valid candidate before shrinking.',baseline:'Enumerating and summing all groups repeats work. Each pointer moves only forward, so the optimized scan takes O(n) time. Negative numbers would break this movement rule.'},complexity:'O(n) time · O(1) extra space',
    code:lines([['def','def minSubArrayLen(target, nums):'],['init','    left, total, best = 0, 0, float("inf")'],['loop','    for right in range(len(nums)):'],['add','        total += nums[right]'],['valid','        while total >= target:'],['save','            best = min(best, right - left + 1)'],['remove','            total -= nums[left]'],['remove','            left += 1'],['done','    return 0 if best == float("inf") else best']]),
    practices:[{prompt:'nums = [1, 2, 3, 4], target = 6. What is the shortest valid length?',answer:2,question:'Why shrink after reaching the target?',options:['To look for a shorter valid window.','To sort the values.','To guarantee the sum increases.'],correct:0,hint:'[3, 4] reaches the target with two items.',explanation:'Length 2 works; no single value reaches 6. Positive values make the shrinking rule reliable.'},{prompt:'nums = [1, 1, 1], target = 5. What should be returned?',answer:0,question:'What does zero mean here?',options:['The first element wins.','No contiguous group reaches the target.','The target is zero.'],correct:1,hint:'Even all three values sum to only 3.',explanation:'Return 0 when there is no valid group. Do not report an invented empty winning range.'}]
  },
  {
    id:'unique-substring',version:1,number:3,slug:'longest-substring-without-repeating-characters',title:'Longest Substring Without Repeating Characters',shortTitle:'One of each',pattern:'Variable-size window',difficulty:'Medium',inputKind:'text',defaults:{raw:'abcabcbb',parameter:''},presets:[{label:'Repeated letters',input:{raw:'bbbbb',parameter:''}},{label:'Empty string',input:{raw:'',parameter:''}}],inputHint:'0–16 printable ASCII characters, including spaces. Spaces count as characters.',prerequisites:'Recommended: Pack just enough.',objective:'Maintain a uniqueness rule while growing and shrinking a window.',story:{title:'A guest list with no duplicate names.',paragraphs:['A moving guest list follows a line of arriving characters. Each character may appear only once in the list. You want the longest valid list.','When a duplicate arrives, remove guests from the left until the duplicate is resolved. Then compare the valid list’s length with your record.'],mapping:'Guest list = contiguous substring. Name count = character frequency in the current window.',invariant:'Save a candidate only when every character count is at most 1. Shrinking must continue until the duplicate is removed.',baseline:'Checking each possible substring repeats scans. With a frequency table and forward-moving boundaries, each character enters and leaves at most once.'},complexity:'O(n) time · O(min(n, alphabet)) extra space',
    code:lines([['def','def lengthOfLongestSubstring(s):'],['init','    counts, left, best = {}, 0, 0'],['loop','    for right, char in enumerate(s):'],['add','        counts[char] = counts.get(char, 0) + 1'],['valid','        while counts[char] > 1:'],['remove','            counts[s[left]] -= 1'],['remove','            left += 1'],['save','        best = max(best, right - left + 1)'],['done','    return best']]),
    practices:[{prompt:'s = "abba". What is the longest unique substring length?',answer:2,question:'What must happen when the second b enters?',options:['Save the invalid length 3.','Remove from the left until the duplicate b is gone.','Delete every b from the input.'],correct:1,hint:'"ab" and "ba" are valid; "abb" is not.',explanation:'The answer is 2. Removing only a does not fix the duplicate b; shrinking must continue.'},{prompt:'s = "" (an empty string). What length should be returned?',answer:0,question:'What should the final view show?',options:['An invented character.','An empty selection and result 0.','An error for every empty string.'],correct:1,hint:'There are no characters to include.',explanation:'An empty input has a longest unique substring length of 0.'}]
  },
  {
    id:'two-sum',version:1,number:167,slug:'two-sum-ii-input-array-is-sorted',title:'Two Sum II — Input Array Is Sorted',shortTitle:'Meet in the middle',pattern:'Two pointers',difficulty:'Medium',inputKind:'numbers',parameter:'Target',defaults:{raw:'2, 7, 11, 15',parameter:'9'},presets:[{label:'Move left pointer',input:{raw:'1, 3, 5, 9',parameter:'14'}},{label:'Negative pair',input:{raw:'-4, -1, 2, 6',parameter:'1'}}],inputHint:'2–16 sorted integers from −1,000 to 1,000. Target in that range; exactly one index pair must match.',prerequisites:'Recommended: fixed-window lessons; understand sorted arrays.',objective:'Use sorted order to rule out pairs with one pointer move.',story:{title:'Meet at exactly the right total.',paragraphs:['Two shoppers stand at opposite ends of a sorted price shelf. Together they need an exact total, using two different items.','If the total is too small, the left shopper needs a larger value. If it is too large, the right shopper needs a smaller one. The middle values are not part of the selected pair.'],mapping:'Shoppers = left and right pointers. Selected pair = two individual positions, not a full window.',invariant:'If the sum is too small, the current left value cannot work with any remaining right value. The symmetric rule removes the current right when the sum is too large.',baseline:'Trying every pair costs O(n²). Sorted order lets us discard a boundary each time, reaching O(n). Return 1-based positions, not the values.'},complexity:'O(n) time · O(1) extra space',
    code:lines([['def','def twoSum(numbers, target):'],['init','    left, right = 0, len(numbers) - 1'],['loop','    while left < right:'],['sum','        total = numbers[left] + numbers[right]'],['found','        if total == target:'],['done','            return [left + 1, right + 1]'],['small','        if total < target:'],['left','            left += 1'],['else','        else:'],['right','            right -= 1']]),
    practices:[{prompt:'numbers = [1, 3, 5, 9], target = 14. Enter the two 1-based positions, separated by a comma.',answer:[3,4],question:'When the pair sum is below the target, which pointer moves?',options:['Right moves left.','Left moves right.','Both move randomly.'],correct:1,hint:'5 + 9 = 14. Return their positions, not their values.',explanation:'The positions are 3 and 4. Moving left to a larger value increases the sum.'},{prompt:'numbers = [-4, -1, 2, 6], target = 1. Enter the two 1-based positions.',answer:[2,3],question:'Are the values between the pointers added to the pair sum?',options:['Yes, all values in the range.','No, only the two pointed values.','Only negative values.'],correct:1,hint:'−1 + 2 = 1.',explanation:'Return [2, 3]. This selects a pair, not a contiguous subarray sum.'}]
  }
];
export const getLesson = (id: string) => lessons.find(lesson=>lesson.id===id || lesson.slug===id);
