'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Search, Sparkles, Play, ChevronLeft, ChevronRight, LockKeyhole, Check, Bookmark, Layers3 } from 'lucide-react';
import { lessons } from '@/lessons/catalog';
import catalog from '@/data/problems.json';
import { decodeProgress, emptyProgress, PROGRESS_KEY, restoreLesson, type Progress } from '@/lib/progress';
import { AcademyShell } from './academy-shell';
const values=[1,12,-5,-6,50,3];
export function LearningLibrary(){
 const [query,setQuery]=useState(''),[difficulty,setDifficulty]=useState('All difficulties'),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[start,setStart]=useState(1);
 const [confirmReset,setConfirmReset]=useState(false);
 const [saved,setSaved]=useState<string[]>([]),[progress,setProgress]=useState<Progress>(emptyProgress),[notice,setNotice]=useState('');
 useEffect(()=>{try{setProgress(decodeProgress(localStorage.getItem(PROGRESS_KEY)));const data=JSON.parse(localStorage.getItem('leetlove.bookmarks')??'[]');if(Array.isArray(data))setSaved(data.filter((v:unknown)=>typeof v==='string'));}catch{setNotice('Storage is unavailable. Changes last for this session.');}},[]);
 const summaries=lessons.map(lesson=>({lesson,...restoreLesson(lesson,progress.lessons[lesson.id])}));
 const completed=summaries.filter(s=>s.practices.length===s.lesson.practices.length).length;
 const next=summaries.find(s=>s.restored&&s.practices.length<s.lesson.practices.length)?.lesson??lessons[0];
 const filtered=useMemo(()=>catalog.problems.filter(p=>(`${p.number} ${p.title}`.toLowerCase().includes(query.trim().toLowerCase()))&&(difficulty==='All difficulties'||p.difficulty===difficulty)&&(filter==='all'||filter==='visual'&&lessons.some(l=>l.slug===p.slug)||filter==='saved'&&saved.includes(p.slug))),[query,difficulty,filter,saved]);
 const pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(page,pages-1);
 function bookmark(slug:string){const updated=saved.includes(slug)?saved.filter(s=>s!==slug):[...saved,slug];setSaved(updated);try{localStorage.setItem('leetlove.bookmarks',JSON.stringify(updated));}catch{setNotice('Bookmarks could not be saved in this browser.');}}
 return <AcademyShell><main className="catalog-main">
 <div className="catalog-intro"><div><div className="product-eyebrow"><i/> A DIFFERENT WAY TO LEETCODE</div><h1>Less memorizing.<br/>More <span>understanding.</span></h1><p>Your next breakthrough starts with seeing the solution.</p></div><div className="intro-mark" aria-hidden="true">{'{ }'}<Sparkles size={25}/></div></div>
 <section className="discovery-hero"><div className="hero-copy"><span className="hero-label"><Sparkles size={14}/> ALGORITHMS, BROUGHT TO LIFE</span><h2>Don’t just read the code.<br/>See the idea in motion.</h2><p>Move the pointers. Follow the logic. Build the intuition that stays with you when the problem changes.</p><Link href={`/learn/${next.slug}`} className="button primary">Explore a visual solution <ArrowRight size={16}/></Link><span className="hero-footnote">Interactive steps · Python walkthroughs · Hands-on practice</span></div><div className="window-preview"><div className="preview-top"><span><i/> Sliding window</span><span>LIVE PREVIEW</span></div><div className="preview-array">{values.map((v,i)=><div key={i} className={i>=start&&i<start+4?'in-window':''}><small>{i}</small><strong>{v}</strong><span>{i===start?'L':i===start+3?'R':' '}</span></div>)}</div><div className="preview-bottom"><div><small>WINDOW AVERAGE</small><strong>{(values.slice(start,start+4).reduce((a,b)=>a+b,0)/4).toFixed(2)}</strong></div><button onClick={()=>setStart((start+1)%3)}>Slide the window <ArrowRight size={15}/></button></div><div className="preview-caption">Remove the outgoing value. Add the incoming one.</div></div></section>
 <div className="catalog-metrics"><div><Layers3 size={19}/><strong>{catalog.problems.length.toLocaleString('en-US')}</strong><span>problems to explore</span></div><div><Sparkles size={19}/><strong>{lessons.length}</strong><span>visual solutions</span></div><div><Check size={19}/><strong>{completed}/{lessons.length}</strong><span>practices completed</span></div></div>
 <section className="problem-section" id="problems"><div className="catalog-section-title"><div><h2>Find your next challenge</h2><p>One catalog. A clearer path to the aha moment.</p></div><span className="coverage-note"><i/> Visual library is growing</span></div><div className="catalog-controls"><div className="catalog-tabs" role="group" aria-label="Problem collection">{[['all','All problems'],['visual','Visual solutions'],['saved','Bookmarked']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setPage(0);}}>{id==='visual'&&<Sparkles size={14}/>} {label}{id==='visual'&&<span>{lessons.length}</span>}</button>)}</div><div className="catalog-search-row"><label className="catalog-search"><Search size={18}/><input aria-label="Search problems" placeholder="Search by problem title or number…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label="Filter difficulty" value={difficulty} onChange={e=>{setDifficulty(e.target.value);setPage(0);}}>{['All difficulties','Easy','Medium','Hard'].map(d=><option key={d}>{d}</option>)}</select></div></div>
 <div className="problem-table-wrap"><table className="problem-table"><thead><tr><th scope="col">PROBLEM</th><th scope="col">DIFFICULTY</th><th scope="col">ACCEPTANCE</th><th scope="col">LEETLOVE SOLUTION</th><th scope="col"><span className="sr-only">Bookmark</span></th></tr></thead><tbody>{filtered.slice(current*20,current*20+20).map(p=>{const lesson=lessons.find(l=>l.slug===p.slug);return <tr key={p.slug}><td><div className="problem-name"><span className="problem-number">{p.number}</span><Link href={`/problems/${p.slug}`}>{p.title}</Link>{p.premium&&<LockKeyhole size={12} aria-label="LeetCode Premium"/>}</div></td><td><span className={`level ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span></td><td className="acceptance">{p.acceptance}%</td><td>{lesson?<Link className="visual-badge" href={`/learn/${lesson.slug}`}><Play size={12} fill="currentColor"/> Visual solution <ArrowRight size={13}/></Link>:<span className="not-available">Not available yet</span>}</td><td><button className={`bookmark-button ${saved.includes(p.slug)?'saved':''}`} aria-label={`${saved.includes(p.slug)?'Remove bookmark for':'Bookmark'} ${p.title}`} aria-pressed={saved.includes(p.slug)} onClick={()=>bookmark(p.slug)}><Bookmark size={16} fill={saved.includes(p.slug)?'currentColor':'none'}/></button></td></tr>;})}</tbody></table></div>
 {!filtered.length&&<div className="catalog-empty"><Search size={28}/><h3>{filter==='saved'&&!saved.length?'Your next challenge, saved for later.':'No matching problems'}</h3><p>{filter==='saved'&&!saved.length?'Use the bookmark icon on any problem to keep it here.':'Try another title, number, or difficulty.'}</p><button className="button secondary" onClick={()=>{setQuery('');setDifficulty('All difficulties');setFilter('all');setPage(0);}}>Show all problems</button></div>}
 <div className="catalog-pagination"><span role="status">{filtered.length?`${current*20+1}–${Math.min((current+1)*20,filtered.length)} of ${filtered.length.toLocaleString('en-US')} problems`:'0 problems'}</span><div><button aria-label="Previous page" disabled={!current} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></button><span>{current+1} / {pages}</span><button aria-label="Next page" disabled={current+1===pages} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></button></div></div></section><footer className="catalog-footer"><span>{notice||'Bookmarks and learning progress are saved on this device.'}</span><a href="https://leetcode.com/problemset/" target="_blank" rel="noreferrer">LeetCode catalog · {catalog.fetchedAt.slice(0,10)}</a></footer><div className="catalog-reset">{confirmReset?<><span>Clear saved lesson runs and practice results on this device?</span><button onClick={()=>{try{localStorage.removeItem(PROGRESS_KEY);setProgress(emptyProgress());setNotice('Learning progress cleared.');}catch{setNotice('Could not clear saved progress.');}setConfirmReset(false);}}>Clear learning progress</button><button onClick={()=>setConfirmReset(false)}>Cancel</button></>:<button onClick={()=>setConfirmReset(true)}>Reset learning progress</button>}</div>
 </main></AcademyShell>;
}
