'use client';
import Link from 'next/link';
import { useEffect, useReducer, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, Code2, ExternalLink, Pause, Play, RotateCcw, Sparkles } from 'lucide-react';
import { getLesson, lessons } from '@/lessons/catalog';
import { buildTrace, checkPractice } from '@/lessons/engine';
import { initialPlayer, playerReducer } from '@/lib/player';
import { decodeProgress, PROGRESS_KEY, restoreLesson, saveLesson } from '@/lib/progress';
import { AcademyShell } from './academy-shell';
import { LessonCanvas } from './lesson-canvas';
import { ExecutionMap } from './execution-map';
import { PythonCode } from './python-code';

export function LessonPlayer({id}:{id:string}) {
  const lesson=getLesson(id)!;
  const [state,dispatch]=useReducer(playerReducer,undefined,()=>initialPlayer(lesson.defaults,buildTrace(lesson,lesson.defaults)));
  const [draft,setDraft]=useState(lesson.defaults);const [tab,setTab]=useState('studio');const [error,setError]=useState('');const [ready,setReady]=useState(false);const [storageNote,setStorageNote]=useState('Progress is saved in this browser only.');
  const [passed,setPassed]=useState<number[]>([]);const [answers,setAnswers]=useState<Record<number,string>>({});const [reasons,setReasons]=useState<Record<number,number>>({});const [practiceFeedback,setPracticeFeedback]=useState<Record<number,string>>({});const [prediction,setPrediction]=useState('');const [predictionNote,setPredictionNote]=useState('');
  const frame=state.frames[state.step],nextLesson=lessons[lessons.indexOf(lesson)+1];
  useEffect(()=>{try{const p=decodeProgress(localStorage.getItem(PROGRESS_KEY));const restored=restoreLesson(lesson,p.lessons[lesson.id]);dispatch({type:'load',state:restored.state});setDraft(restored.state.input);setPassed(restored.practices);if(restored.restored)setStorageNote('Resumed your saved run. Progress stays in this browser.');if(restored.discarded)setStorageNote('The previous run could not be restored. Started a fresh lesson.');}catch{setStorageNote('Storage is unavailable. This session will not be saved.');}setReady(true);},[lesson]);
  useEffect(()=>{if(!ready)return;try{const p=decodeProgress(localStorage.getItem(PROGRESS_KEY));p.lessons[lesson.id]=saveLesson(lesson,state,passed);localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));}catch{setStorageNote('Storage is unavailable. You can continue without saved progress.');}},[ready,lesson,state.input,state.step,state.furthest,state.mode,passed]);
  useEffect(()=>{if(!state.playing)return;const timer=setTimeout(()=>dispatch({type:'next',from:state.step}),state.speed);return()=>clearTimeout(timer);},[state.playing,state.step,state.speed]);
  useEffect(()=>{setPrediction('');setPredictionNote('');},[state.step,state.input]);
  function apply(input=draft){try{const frames=buildTrace(lesson,input);dispatch({type:'load',state:{...initialPlayer(input,frames),mode:state.mode,speed:state.speed}});setDraft(input);setError('');}catch(e){setError((e as Error).message);}}
  function changeTab(value:string){dispatch({type:'pause'});setTab(value);}
  const check=(i:number)=>{const p=lesson.practices[i];if(checkPractice(answers[i]??'',p.answer)&&reasons[i]===p.correct){setPassed(old=>[...new Set([...old,i])]);setPracticeFeedback(old=>({...old,[i]:`Correct. ${p.explanation}`}));}else setPracticeFeedback(old=>({...old,[i]:`Keep thinking. ${p.hint} Also check the reason for your answer.`}));};
  return <AcademyShell active={lesson.id}><main className="lesson-main"><div className="lesson-heading"><div><div className="eyebrow">LESSON 0{lessons.indexOf(lesson)+1} / {lesson.pattern.toUpperCase()}</div><h1>{lesson.title}</h1><p>{lesson.objective}</p></div><a className="source-link" href={`https://leetcode.com/problems/${lesson.slug}/`} target="_blank" rel="noreferrer">LC {lesson.number}<ExternalLink size={13}/></a></div><div className="lesson-meta"><span className="difficulty">{lesson.difficulty}</span><span>{lesson.complexity}</span><span>{passed.length}/2 practice checks</span><button className="focus-button" onClick={()=>{changeTab('studio');requestAnimationFrame(()=>{const studio=document.getElementById('focus-lab');studio?.focus({preventScroll:true});studio?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});}}>Focus the lesson <ArrowRight size={13}/></button></div><nav className="lesson-tabs" aria-label="Lesson sections">{[['story','The story',BookOpen],['studio','Interactive studio',Play],['practice','Try it yourself',Code2]].map(([value,label,Icon])=>{const I=Icon as typeof BookOpen;return <button key={String(value)} aria-current={tab===value?'page':undefined} className={tab===value?'active':''} onClick={()=>changeTab(String(value))}><I size={16}/>{String(label)}</button>;})}</nav>
    {tab==='story'&&<section className="story-page"><span className="story-symbol"><BookOpen size={30}/></span><div className="eyebrow">BUILD A MENTAL MODEL</div><h2>{lesson.story.title}</h2>{lesson.story.paragraphs.map(p=><p key={p}>{p}</p>)}<div className="story-mapping">{lesson.story.mapping}</div><h3>The rule we protect</h3><p>{lesson.story.invariant}</p><h3>Why reuse the work?</h3><p>{lesson.story.baseline}</p><p className="prerequisite">{lesson.prerequisites}</p><button className="button primary" onClick={()=>changeTab('studio')}>Bring the story to life <ArrowRight size={16}/></button></section>}
    {tab==='studio'&&<div className="studio-layout"><section className="studio-card" id="focus-lab" tabIndex={-1}><div className="studio-toolbar"><div className="mode-toggle" role="group" aria-label="Learning mode"><button className={state.mode==='guided'?'active':''} aria-pressed={state.mode==='guided'} onClick={()=>dispatch({type:'mode',mode:'guided'})}>Hands-on</button><button className={state.mode==='watch'?'active':''} aria-pressed={state.mode==='watch'} onClick={()=>dispatch({type:'mode',mode:'watch'})}>Watch & explore</button></div><span>STEP {state.step+1} / {state.frames.length}</span></div><div className="transport"><button aria-label="Reset run" title="Reset run; keep completed practice" onClick={()=>dispatch({type:'reset'})}><RotateCcw size={16}/></button><button aria-label="Previous step" disabled={state.step===0} onClick={()=>dispatch({type:'seek',step:state.step-1})}><ArrowLeft size={16}/></button><button className="play-control" aria-label={state.playing?'Pause':'Play'} disabled={state.mode==='guided'||state.step===state.frames.length-1} title={state.mode==='guided'?'Switch to Watch & explore to play':'Play or pause'} onClick={()=>dispatch({type:'play'})}>{state.playing?<Pause size={16}/>:<Play size={16}/>}</button><button aria-label="Next step" disabled={state.mode==='guided'||state.step===state.frames.length-1} onClick={()=>dispatch({type:'next',from:state.step})}><ArrowRight size={16}/></button><input aria-label="Execution timeline" type="range" min="0" max={state.frames.length-1} value={state.step} onChange={e=>dispatch({type:'seek',step:Number(e.target.value)})}/><select aria-label="Playback speed" value={state.speed} onChange={e=>dispatch({type:'speed',speed:Number(e.target.value)})}><option value="2400">0.5×</option><option value="1200">1×</option><option value="600">2×</option></select></div>
    <ExecutionMap state={state} dispatch={dispatch}/><LessonCanvas lesson={lesson} state={state} dispatch={dispatch}/>
    <details className="input-editor"><summary>Experiment with the input <span>{state.input.raw||'(empty)'}{lesson.parameter?` · ${lesson.parameter} = ${state.input.parameter}`:''}</span></summary><form onSubmit={e=>{e.preventDefault();apply();}}><label>{lesson.inputKind==='text'?'String':'Array'}<input aria-label={lesson.inputKind==='text'?'String input':'Array input'} value={draft.raw} onChange={e=>setDraft({...draft,raw:e.target.value})}/></label>{lesson.parameter&&<label className="parameter-input">{lesson.parameter}<input aria-label={lesson.parameter} value={draft.parameter} onChange={e=>setDraft({...draft,parameter:e.target.value})}/></label>}<button className="button secondary" type="submit">Apply input <ArrowRight size={14}/></button></form><p>{lesson.inputHint}</p><div className="preset-row"><button onClick={()=>apply(lesson.defaults)}>Default example</button>{lesson.presets.map(p=><button key={p.label} onClick={()=>apply(p.input)}>{p.label}</button>)}</div>{error&&<p className="input-error" role="alert">{error}</p>}</details>
    {frame.tone==='done'&&<div className="completion-callout"><Check size={20}/><div><strong>You explored the solution.</strong><p>Now solve a fresh example without the canvas.</p></div><button onClick={()=>changeTab('practice')}>Try it yourself <ArrowRight size={16}/></button></div>}
    </section><aside className="code-pane"><div className="code-header"><Code2 size={17}/><h2>Behind the scenes</h2><span>Python</span></div><pre aria-label="Python solution">{lesson.code.map((line,i)=><div key={`${line.id}-${i}`} className={line.id===frame.op?'active':''} aria-current={line.id===frame.op?'step':undefined}><span>{i+1}</span><code><PythonCode code={line.text}/></code></div>)}</pre><div className="invariant"><span className="eyebrow">THE RULE WE PROTECT</span><p>{lesson.story.invariant}</p><small>{lesson.complexity}</small></div><div className="prediction-box"><Sparkles size={18}/><h3>Pause & predict</h3><p>Before moving on, predict the final {lesson.id==='two-sum'?'1-based positions':'answer'} for this input.</p><form onSubmit={e=>{e.preventDefault();dispatch({type:'pause'});const result=state.frames.at(-1)!.result!;setPredictionNote(checkPractice(prediction,result)?'Correct prediction. Can you explain why?':'Not yet. Follow the invariant and compare the candidates.');}}><input aria-label="Predicted answer" placeholder={lesson.id==='two-sum'?'e.g. 1, 2':'Your prediction'} value={prediction} onFocus={()=>dispatch({type:'pause'})} onChange={e=>setPrediction(e.target.value)}/><button>Check</button></form>{predictionNote&&<p role="status">{predictionNote}</p>}</div></aside></div>}
    {tab==='practice'&&<section className="practice-page"><div className="eyebrow">THINK WITHOUT THE CANVAS</div><h2>Make the idea your own.</h2><p>Two fresh examples. An answer and a reason. Playback alone never marks these complete.</p>{lesson.practices.map((p,i)=><form className="practice-card" key={i} onSubmit={e=>{e.preventDefault();check(i);}}><div className="practice-top"><span>CHALLENGE 0{i+1}</span>{passed.includes(i)&&<span><Check size={14}/> Completed</span>}</div><h3>{p.prompt}</h3><label>Your answer<input aria-label={`Challenge ${i+1} answer`} required value={answers[i]??''} onChange={e=>setAnswers({...answers,[i]:e.target.value})}/></label><fieldset><legend>{p.question}</legend>{p.options.map((option,n)=><label key={option}><input required type="radio" name={`reason-${i}`} checked={reasons[i]===n} onChange={()=>setReasons({...reasons,[i]:n})}/>{option}</label>)}</fieldset><button className="button primary">Check understanding <Check size={15}/></button><details><summary>A small hint</summary><p>{p.hint}</p></details>{practiceFeedback[i]&&<p className="practice-feedback" role="status">{practiceFeedback[i]}</p>}</form>)}{passed.length===2&&<div className="practice-complete"><Check size={24}/><h3>Practice completed.</h3><p>You answered both examples and their explanation checks.</p><Link className="button primary" href={nextLesson?`/learn/${nextLesson.slug}`:'/'}>{nextLesson?`Next: ${nextLesson.shortTitle}`:'Back to the learning library'}<ArrowRight size={16}/></Link></div>}</section>}
    <footer className="lesson-footer"><span role="status">{storageNote}</span><Link href="/">All lessons <ArrowRight size={13}/></Link></footer></main></AcademyShell>;
}
