'use client';
import { useEffect, useRef, useState } from 'react';
import { Hand, Trophy, MousePointer2 } from 'lucide-react';
import type { Lesson, Snapshot } from '@/lessons/types';
import type { PlayerState, PlayerAction } from '@/lib/player';
import { parseLessonInput } from '@/lessons/engine';
export function LessonCanvas({lesson,state,dispatch}:{lesson:Lesson;state:PlayerState;dispatch:React.Dispatch<PlayerAction>}) {
  const frame=state.frames[state.step],next=state.frames[state.step+1],done=frame.tone==='done',guided=state.mode==='guided';
  const {values}=parseLessonInput(lesson,state.input);const [inspected,setInspected]=useState<number|null>(null);const scroller=useRef<HTMLDivElement>(null);
  const challenge=next?.challenge;const selected=frame.selected;
  useEffect(()=>{setInspected(null);const target=done?selected[0]:frame.focus;const el=scroller.current;if(el&&target!==undefined){const x=target*70;if(x<el.scrollLeft||x+70>el.scrollLeft+el.clientWidth)el.scrollTo({left:Math.max(0,x+78-el.clientWidth),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}},[state.step,state.input,done,frame.focus,selected]);
  const choose=(key:string)=>dispatch({type:'choose',key,from:state.step});
  return <div className="lesson-canvas" id="focus-lab" tabIndex={-1}>
    <div className={`action-area ${done?'finished':''}`}><div className="action-icon">{done?<Trophy size={21}/>:guided?<Hand size={21}/>:<MousePointer2 size={21}/>}</div><div className="action-content"><div className="eyebrow">{done?'YOU FOUND THE ANSWER':guided?'YOUR MOVE':'WATCH & EXPLORE'}</div><h2>{done?frame.title:guided?challenge?.prompt:'Inspect a value or play the next step.'}</h2><p>{done?frame.explanation:guided?challenge?.kind==='cell'?'Choose a value in the array below. Think before you move.':'Choose the action that preserves the rule.':'Click any value to inspect its role. Playback controls are just above.'}</p>{guided&&challenge?.kind==='choice'&&<div className="action-choices">{challenge.options?.map(option=><button key={option.key} onClick={()=>choose(option.key)}>{option.label}</button>)}</div>}{state.feedback&&<p className="answer-feedback" role="status">{state.feedback}</p>}</div></div>
    <div className="canvas-heading"><span>{frame.range?'THE VIEWFINDER':'THE TWO POINTERS'}</span><span>{done?'★ Result highlighted':frame.range?`${selected.length} value${selected.length===1?'':'s'} selected`:'Only the two endpoints count'}</span></div>
    <div className="data-scroll" ref={scroller}><div className="data-track" style={{width:Math.max(values.length,1)*70+16}}>
      {frame.range&&selected.length>0&&<div className={`selection-frame ${done?'gold':''}`} style={{left:selected[0]*70+5,width:selected.length*70-2}} aria-hidden="true"><span>{done?'WINNING RANGE':'CURRENT WINDOW'}</span></div>}
      {values.length===0?<div className="empty-data">∅ <span>Empty input · no values to select</span></div>:values.map((value,index)=>{const inside=selected.includes(index),best=frame.best.includes(index),focus=frame.focus===index;return <div className="data-column" key={index}><span className="pointer-label">{frame.pointers.filter(p=>p.index===index).map(p=>p.label).join(' · ')}</span><button className={`data-cell ${inside?done?'winner':'selected':''} ${focus&&!done?frame.tone:''} ${inspected===index?'inspected':''}`} aria-label={`Value ${value===' '?'space':value} at index ${index}`} aria-pressed={inspected===index} onClick={()=>{if(guided&&challenge?.kind==='cell')choose(String(index));else setInspected(index);}}><span>{value===' '?'␣':value}</span>{focus&&!done&&(frame.tone==='add'||frame.tone==='remove')&&<small>{frame.tone==='add'?'IN':'OUT'}</small>}</button><span className="data-index">{index}</span><span className={`record-marker ${best?'visible':''}`}>{frame.best[0]===index?'★ BEST':'━'}</span></div>;})}
    </div></div><div className="canvas-legend"><span><i className="green-dot"/>Current selection</span><span><i className="purple-dot"/>Incoming</span><span><i className="amber-dot"/>Outgoing</span><span>★ Saved answer</span></div>
    {inspected!==null&&<p className="inspect-note" role="status">Input[{inspected}] = {JSON.stringify(values[inspected])} · {selected.includes(inspected)?'Selected':'Not selected'}{lesson.id==='maximum-vowels'?` · vowel contribution: ${'aeiou'.includes(String(values[inspected]))?1:0}`:''}</p>}
    <div className="current-code"><span>PYTHON · CURRENT OPERATION</span><code>{lesson.code.filter(line=>line.id===frame.op).map(line=>line.text.trim()).join(' → ')}</code></div>
    <div className={`arithmetic ${done?'result':''}`}><span className="eyebrow">{done?'THE RESULT':frame.tone==='save'?'COMPARE THE CANDIDATE':'WHAT CHANGED'}</span><strong key={frame.id}>{frame.equation}</strong><p>{frame.explanation}</p></div>
    {frame.memory&&<div className="memory-panel"><span>CHARACTER COUNTS</span><div>{frame.memory.length?frame.memory.map(item=><span className={item.invalid?'duplicate':''} key={item.label}>{item.label}<b>{item.value}</b>{item.invalid&&<small>duplicate</small>}</span>):<em>No characters in the list.</em>}</div></div>}
    <div className="stat-grid">{frame.metrics.map(metric=><div key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong></div>)}</div>
    <details className="notebook" open><summary>Exploration notebook <span>Revisit any checked candidate</span></summary><div>{state.frames.map((item,i)=>item.checkpoint?<button key={item.id} disabled={i>state.furthest} className={i===state.step?'current':''} onClick={()=>dispatch({type:'seek',step:i})} aria-label={`Revisit candidate ${state.frames.slice(0,i+1).filter(f=>f.checkpoint).length}`}><span>{item.checkpoint.label}</span><strong>{i<=state.furthest?item.checkpoint.value:'—'}</strong><small>{i<=state.furthest?'checked':'unexplored'}</small></button>:null)}</div></details>
  </div>;
}
