'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Pause, Play, RotateCcw, Sparkles } from 'lucide-react';
import type { Artifact, JsonValue } from '@/submissions/contracts';
const show=(value:JsonValue|undefined)=>value===undefined?'—':typeof value==='string'?JSON.stringify(value):JSON.stringify(value);
export function SolutionReplay({artifact,sample=false}:{artifact:Omit<Artifact,'source'>&{source?:string};sample?:boolean}){
  const [step,setStep]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1200),[prediction,setPrediction]=useState(''),[feedback,setFeedback]=useState('');
  const frames=artifact.trace.events,event=frames[step],previous=frames[Math.max(0,step-1)],next=frames[step+1],sourceRef=useRef<HTMLPreElement>(null);
  const chapter=[...artifact.story.chapters].reverse().find(c=>c.eventId<=event.id)??artifact.story.chapters[0];
  const predictKey=next&&Object.keys(next.locals).find(key=>Object.hasOwn(event.locals,key)&&!Array.isArray(next.locals[key])&&typeof next.locals[key]!=='object'&&show(next.locals[key])!==show(event.locals[key]));
  const jump=(n:number)=>{setPlaying(false);setStep(n);setPrediction('');setFeedback('');};
  useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{setStep(n=>Math.min(n+1,frames.length-1));setFeedback('');if(step>=frames.length-2)setPlaying(false);},speed);return()=>clearTimeout(timer);},[playing,step,speed,frames.length]);
  useEffect(()=>{const pre=sourceRef.current,line=pre?.querySelector<HTMLElement>('[aria-current="step"]');if(pre&&line&&(line.offsetTop<pre.scrollTop||line.offsetTop+30>pre.scrollTop+pre.clientHeight))pre.scrollTop=Math.max(0,line.offsetTop-pre.clientHeight/2);},[step]);
  return <section className="replay" aria-label="Solution story and execution">
    <div className="story-cover"><span className="eyebrow">{sample?'RECORDED EXAMPLE · REPOSITORY-OWNED CODE':'YOUR SOLUTION, EXPLAINED'}</span><h2>{artifact.story.title}</h2><p>{artifact.story.premise}</p><div className="story-mappings">{artifact.story.mappings.map(m=><span key={m.variable}><code>{m.variable}</code><span>{m.role}</span></span>)}</div></div>
    <div className="replay-grid"><div className="execution-card">
      <div className="execution-toolbar"><strong>Execution studio</strong><span>{step+1} / {frames.length} frames</span></div>
      <div className="execution-controls"><button aria-label="Restart execution" onClick={()=>jump(0)}><RotateCcw size={17}/></button><button aria-label="Previous execution step" disabled={!step} onClick={()=>jump(step-1)}><ArrowLeft size={17}/></button><button className="play-control" aria-label={playing?'Pause execution':'Play execution'} disabled={step===frames.length-1} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Next execution step" disabled={!next} onClick={()=>jump(step+1)}><ArrowRight size={17}/></button><input aria-label="Execution frame" type="range" min={0} max={frames.length-1} value={step} onChange={e=>jump(Number(e.target.value))}/><select aria-label="Execution speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={2400}>0.5×</option><option value={1200}>1×</option><option value={600}>2×</option></select></div>
      <div className="scene-caption"><Sparkles size={16}/><div><strong>{chapter.title}</strong><p>{chapter.narration}</p></div></div>
      <div className="line-context"><span>{event.kind==='return'?'RETURN RECORDED':`ABOUT TO EXECUTE LINE ${event.line}`}</span><code>{artifact.source?.split('\n')[event.line-1]?.trim()??`Original source line ${event.line} · source not shared`}</code></div>
      <div className="value-stage">{Object.entries(event.locals).map(([key,value])=>{
        const changed=show(previous.locals[key])!==show(value),collection=event.collections?.[key];
        return <div key={key} className={`variable-panel ${changed?'changed':''}`}><div className="variable-heading"><code>{key}</code><span>{collection?`${collection.kind} · object ${collection.ref}`:typeof value}{changed?' · changed':''}</span></div>{Array.isArray(value)?<div className="trace-array" tabIndex={0} aria-label={`${key} values, scroll horizontally`}>{value.length?value.map((item,i)=><div className={Array.isArray(previous.locals[key])&&show((previous.locals[key] as JsonValue[])[i])!==show(item)?'value-changed':''} key={i}><strong>{show(item)}</strong><small>{collection?.kind==='set'?'member':i}</small></div>):<p>Empty collection</p>}</div>:value!==null&&typeof value==='object'?<dl className="trace-dictionary">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}{!Object.keys(value).length&&<p>Empty dictionary</p>}</dl>:<strong className="scalar-value">{show(value)}</strong>}</div>;
      })}{!Object.keys(event.locals).length&&<p>Local variables appear as your method runs.</p>}</div>
      {event.kind==='return'&&<div className="execution-result"><Check size={22}/><div><span>YOUR CODE RETURNED</span><strong>{show(event.result)}</strong><p>Recorded on this teaching example.</p></div></div>}
      {predictKey&&<form className="trace-prediction" onSubmit={e=>{e.preventDefault();setPlaying(false);const expected=next.locals[predictKey];const correct=String(expected)===prediction.trim()||show(expected)===prediction.trim();if(correct){setStep(step+1);setPrediction('');setFeedback('Correct. The next recorded state confirms your prediction.');}else setFeedback(`Stay on this frame. Read the upcoming line and try the next value of ${predictKey}.`);}}><label htmlFor="trace-prediction">Before stepping: what will <code>{predictKey}</code> become?</label><div><input id="trace-prediction" value={prediction} onFocus={()=>setPlaying(false)} onChange={e=>setPrediction(e.target.value)} placeholder="Predict the next value"/><button>Check prediction</button></div></form>}
      {feedback&&<p role="status" className="prediction-feedback">{feedback}</p>}
    </div><aside className="submitted-code"><div><strong>{artifact.source?'Your original Python':'Source kept private'}</strong><span>Line {event.line}</span></div>{artifact.source?<pre ref={sourceRef} aria-label="Submitted Python source">{artifact.source.split('\n').map((line,i)=><div key={i} aria-current={i+1===event.line?'step':undefined}><span>{i+1}</span><code>{line||' '}</code></div>)}</pre>:<p>The author shared this story and its recorded values without sharing the original code.</p>}<div className="trace-disclosure"><strong>What this view shows</strong><p>Each frame shows values before the highlighted line; the final frame records its return. Built-in calls and comprehensions appear as single operations. Purple marks a changed value.</p><p>{artifact.story.limitation}</p></div><details><summary>Validation details</summary><p>{sample?'This sample was recorded from an authored example; it is not a verdict for your upload.':`${artifact.passed} cases passed in LeetLove suite ${artifact.suiteVersion}. This is not an official LeetCode verdict or proof of correctness.`}</p><p>Python {artifact.trace.runtime}. Example: <code>{JSON.stringify(artifact.trace.input)}</code></p></details></aside></div>
  </section>;
}
