'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { ArrowRight, Check, Code2, FileUp, Globe, LockKeyhole, Play, Sparkles } from 'lucide-react';
import { AcademyShell } from './academy-shell';
import { SolutionReplay } from './solution-replay';
import { getProblem, problems, bruteAverage } from '@/submissions/problems';
import type { Artifact, ExecutionTrace, Job, ProblemId } from '@/submissions/contracts';
import examples from '@/submissions/examples.json';
type Config={ready:boolean;missing:string[];url:string|null;anonKey:string|null;model:string;publishing:boolean};
type Detail=Job&{artifact_hash:string;canRetry:boolean;publication?:{id:string;visible:boolean;include_source:boolean}|null};
const stages=['validating','tracing','generating','checking','ready'];
const captions=['Check solution','Record execution','Write the story','Check the visuals','Ready for you'];
const sampleArtifact=(index:number):Artifact=>({version:1,sourceHash:examples[index].sourceHash,trace:examples[index] as ExecutionTrace,source:index?bruteAverage:getProblem('maximum-average').starter,problem:'maximum-average',suiteVersion:'sample',passed:0,model:'authored sample',promptVersion:'sample',createdAt:'2026-09-22',story:{title:index?'The inspector who checks every view':'A traveling ledger',premise:index?'An inspector walks along a row of stations. At every possible starting point, they open a fresh ledger and count that entire view again. Follow the repeated visits in the original code.':'A clerk carries a ledger along a row of stations. After recording the first group, the clerk subtracts the departing station and adds the arriving station. The record changes only when the new total is better.',mappings:[{variable:'total',role:'The current ledger balance'},{variable:'best',role:index?'The highest average seen':'The strongest balance seen'}],chapters:[{eventId:0,title:'Open the ledger',narration:'The input is ready. Step through the highlighted line to see which values your ledger records.'},{eventId:Math.floor(examples[index].events.length/2),title:index?'Count another view from scratch':'Carry forward the work',narration:index?'The inspector revisits stations for the next candidate. Watch the nested loop update the same ledger.':'The clerk reuses the running total. Watch the departing contribution and the incoming contribution change it.'},{eventId:examples[index].events.length-1,title:'Return the recorded answer',narration:'The final value comes directly from the method return. The story has followed this execution without replacing its approach.'}],limitation:'This is an authored demonstration on a small example. Full correctness and performance require validation against a broader suite.'}});

export function SolutionStudio(){
  const [config,setConfig]=useState<Config|null>(null),[token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [problem,setProblem]=useState<ProblemId>('maximum-average'),[source,setSource]=useState(getProblem('maximum-average').starter),[input,setInput]=useState(JSON.stringify(getProblem('maximum-average').input)),[draftLoaded,setDraftLoaded]=useState(false);
  const [jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<string|null>(null),[job,setJob]=useState<Detail|null>(null),[sample,setSample]=useState<number|null>(null),[consent,setConsent]=useState(false),[includeSource,setIncludeSource]=useState(false),[author,setAuthor]=useState(''),[publishPreview,setPublishPreview]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
  const [reportId,setReportId]=useState(''),[reportText,setReportText]=useState('');
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get('report');if(id&&/^[a-f0-9-]{36}$/i.test(id))setReportId(id);},[]);
  const auth=useRef<SupabaseClient|null>(null),resultRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let live=true,unsubscribe:(()=>void)|undefined;fetch('/api/studio?config=1').then(r=>r.json()).then(async c=>{if(!live)return;setConfig(c);if(c.url&&c.anonKey){const client=createClient(c.url,c.anonKey);auth.current=client;const {data}=await client.auth.getSession();if(live)setToken(data.session?.access_token??'');const subscription=client.auth.onAuthStateChange((_event,session)=>{if(live){setToken(session?.access_token??'');if(!session){setJob(null);setSelected(null);setJobs([]);}}});unsubscribe=()=>subscription.data.subscription.unsubscribe();}}).catch(()=>setMessage('The service is unavailable. Your draft is still editable.'));try{const raw=localStorage.getItem('leetlove.studio.draft');if(raw){const d=JSON.parse(raw);if(problems.some(p=>p.id===d.problem)&&typeof d.source==='string'&&d.source.length<=50000&&typeof d.input==='string'){setProblem(d.problem);setSource(d.source);setInput(d.input);}}}catch{}setDraftLoaded(true);return()=>{live=false;unsubscribe?.();};},[]);
  useEffect(()=>{if(draftLoaded)try{localStorage.setItem('leetlove.studio.draft',JSON.stringify({problem,source,input}));}catch{}},[problem,source,input,draftLoaded]);
  const api=useCallback(async(path='',body?:unknown)=>{const response=await fetch(`/api/studio${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;},[token]);
  const refresh=useCallback(async()=>{if(token)setJobs(await api());},[api,token]);
  useEffect(()=>{if(token)void refresh().catch(e=>setMessage(e.message));},[token,refresh]);
  useEffect(()=>{if(!token||!selected)return;let live=true;const load=()=>api(`?id=${selected}`).then(data=>{if(live)setJob(data);}).catch(e=>{if(live)setMessage(e.message);});void load();const timer=setInterval(load,2500);return()=>{live=false;clearInterval(timer);};},[api,selected,token]);
  useEffect(()=>{setConsent(false);setPublishPreview(false);setConfirmDelete(false);},[selected,job?.artifact_hash]);
  async function authenticate(signup=false){setBusy(true);setMessage('');try{if(!auth.current)throw Error('Sign-in is not available until private storage is configured.');const {data,error}=signup?await auth.current.auth.signUp({email,password}):await auth.current.auth.signInWithPassword({email,password});if(error)throw error;setPassword('');if(!data.session)setMessage('Check your email to confirm your account, then sign in.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function submit(){setBusy(true);setMessage('');try{const args=JSON.parse(input);const data=await api('',{action:'submit',problem,source,input:args,requestId:crypto.randomUUID()});setSelected(data.id);setSample(null);setJob(null);await refresh();}catch(e){setMessage(e instanceof SyntaxError?'Example input must be a JSON argument list.':(e as Error).message);}finally{setBusy(false);}}
  async function mutate(action:string,fields:Record<string,unknown>={}){if(!job)return;setBusy(true);setMessage('');try{await api('',{action,id:job.id,...fields});if(action==='delete'){setJob(null);setSelected(null);setConfirmDelete(false);}else setJob(await api(`?id=${job.id}`));await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  const working=job&&!['ready','failed','cancelled'].includes(job.stage);
  return <AcademyShell active="create"><main className="creator-main">
    <div className="creator-hero"><div><span className="eyebrow">THE SOLUTION STUDIO</span><h1>Your code.<br/><em>Its own story.</em></h1><p>Bring your approach. We’ll check it, follow its execution, and turn the logic into something you can see.</p><div className="creator-promises"><span><LockKeyhole size={14}/> Private first</span><span><Code2 size={14}/> Your actual code</span><span><Globe size={14}/> Share by choice</span></div></div><div className="hero-route" aria-label="Your code becomes a checked story"><span>01 <Code2 size={17}/> YOUR SOLUTION</span><i/><span>02 <Check size={17}/> CHECK & TRACE</span><i/><span>03 <Sparkles size={17}/> YOUR STORY</span></div></div>
    {config&&!config.ready&&<div className="studio-notice" role="status"><strong>Solution generation is currently unavailable.</strong><span>Explore the recorded examples below, or prepare a solution draft to keep on this device. Please try again later to generate a new walkthrough.</span></div>}
    <div className="create-grid"><section className="source-editor"><div className="panel-title"><div><span className="eyebrow">01 / BRING YOUR APPROACH</span><h2>A solution worth understanding.</h2></div><span className="language-pill">Python 3</span></div>
      <label className="field-label" htmlFor="problem-select">LeetCode problem</label><select id="problem-select" value={problem} onChange={e=>{const p=getProblem(e.target.value as ProblemId);setProblem(p.id);setInput(JSON.stringify(p.input));setMessage('Problem changed. Your code was preserved; update its method signature if needed.');}}>{problems.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><div className="signature-line">Expected method <code>{getProblem(problem).signature}</code></div>
      <div className="editor-caption"><label htmlFor="python-source">Your Python solution</label><label className="upload-button"><FileUp size={14}/> Upload .py<input aria-label="Upload Python solution" type="file" accept=".py,text/x-python" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(!file.name.toLowerCase().endsWith('.py')||file.size>50000)throw Error('Choose a .py file no larger than 50 KB.');setSource(new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()));setMessage(`Loaded ${file.name}. Review the code before submitting.`);}catch(err){setMessage((err as Error).message);}e.target.value='';}}/></label></div>
      <textarea id="python-source" value={source} spellCheck={false} onChange={e=>setSource(e.target.value)} aria-describedby="source-support"/>
      <div className="editor-foot"><span>{source.split('\n').length} lines · draft saved on this device</span><button onClick={()=>{setSource(getProblem(problem).starter);setMessage('Loaded the example solution. You can edit it before submitting.');}}>Load starter</button></div>
      <label className="field-label" htmlFor="teaching-input">Teaching example · JSON arguments</label><input id="teaching-input" value={input} onChange={e=>setInput(e.target.value)}/><p className="field-help">Up to 16 values or characters for playback. Validation uses a broader test suite.</p>
      <button className="generate-button" disabled={!config?.ready||!token||busy||!!working} onClick={submit}><Sparkles size={17}/>{busy?'Working…':'Validate & explain my solution'}<ArrowRight size={17}/></button>
      <details id="source-support" className="support-details"><summary>Supported Python & privacy</summary><p>One class Solution and one method. Scalars, arrays, strings, sets, string-key dictionaries, loops and approved built-ins. No imports, helper methods, reflection, file/network access, or external dependencies. Type hints such as List are supplied. Unique-substring currently supports printable ASCII, including spaces.</p><p>Calls and comprehensions are shown as single operations. We do not infer pointers from variable names. Source and a small execution example are processed privately by the sandbox and Groq; hidden tests are never sent to Groq. Public sharing requires your separate consent.</p></details>
    </section><aside className="creator-sidebar"><section className="workflow-card"><span className="eyebrow">02 / WHAT HAPPENS NEXT</span><h2>From logic to an aha.</h2>{[['Check your solution','Examples, edge cases, and generated tests.'],['Follow your execution','Actual source lines and recorded values.'],['Find the story','An analogy grounded in what your code does.'],['Make it yours','Replay privately. Publish only if you choose.']].map(([title,copy],i)=><div className="workflow-step" key={title}><span>{i+1}</span><div><strong>{title}</strong><p>{copy}</p></div></div>)}</section>
      <section className="account-card"><LockKeyhole size={20}/><h3>{token?'Your private workspace':'Keep your work yours.'}</h3>{token?<><p>Your explanations are visible only to you until you publish.</p><button onClick={()=>auth.current?.auth.signOut()}>Sign out</button></>:<><p>Sign in to submit code and return to your explanations.</p><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><div><button disabled={!config?.url||busy} onClick={()=>authenticate()}>Sign in</button><button disabled={!config?.url||busy} onClick={()=>authenticate(true)}>Create account</button></div></>}</section>
    </aside></div>
    {message&&<p className="studio-message" role="status">{message}</p>}
    {reportId&&<section className="job-panel"><h2>Report a public explanation</h2><p>Describe the misleading or inappropriate content. Your report is private.</p><label className="field-label" htmlFor="report-text">What should we review?</label><input id="report-text" value={reportText} maxLength={1000} onChange={e=>setReportText(e.target.value)}/><button disabled={!token||reportText.trim().length<10||busy} onClick={async()=>{setBusy(true);try{await api('',{action:'report',id:reportId,reason:reportText.trim()});setMessage('Your report was saved for review.');setReportId('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Send private report</button>{!token&&<p>Sign in above to submit the report.</p>}</section>}
    {token&&jobs.length>0&&<section className="workspace-history"><div><span className="eyebrow">YOUR PRIVATE WORKSPACE</span><h2>Pick up your explanations.</h2></div><div>{jobs.map(item=><button key={item.id} className={selected===item.id?'selected':''} onClick={()=>{setSelected(item.id);setSample(null);setJob(null);}}><strong>{getProblem(item.problem).title}</strong><span>{item.stage} · {new Date(item.created_at).toLocaleDateString()}</span></button>)}</div></section>}
    {job&&<section className="job-panel" aria-live="polite"><div><span className="private-badge"><LockKeyhole size={13}/> {job.publication?.visible?'Public version available':'Private explanation'}</span><h2>{job.stage==='ready'?'Here are the visuals and story for your solution.':job.stage==='failed'?'This explanation needs attention.':job.stage==='cancelled'?'Your run was cancelled.':'Your approach is taking shape.'}</h2><p>{job.message}</p></div>{working&&<><ol className="job-stages">{captions.map((caption,i)=><li className={stages.indexOf(job.stage)>=i?'active':''} key={caption}><span>{i+1}</span>{caption}</li>)}</ol><button disabled={busy} onClick={()=>mutate('cancel')}>Cancel run</button></>}{job.canRetry&&<button disabled={busy} onClick={()=>mutate('retry')}>Retry saved story generation</button>}</section>}
    {job?.artifact&&job.stage==='ready'&&<div ref={resultRef}><SolutionReplay key={job.artifact_hash} artifact={job.artifact}/><section className="publication-panel"><div><Globe size={22}/><h2>Let someone else have the aha.</h2><p>Preview exactly what you’ll share. Your source is optional.</p></div>{job.publication?.visible?<div><Link href={`/s/${job.publication.id}`}>View public story <ArrowRight size={15}/></Link><button disabled={busy} onClick={()=>mutate('unpublish')}>Unpublish</button></div>:<button onClick={()=>setPublishPreview(!publishPreview)}>{publishPreview?'Close public preview':'Preview publication'}</button>}{publishPreview&&!job.publication?.visible&&<div className="publication-preview"><h3>Your public page will contain</h3><p>{job.artifact.story.title} · the story, variable mappings, recorded teaching input and values, and validation scope.</p><label>Author display name<input value={author} maxLength={60} onChange={e=>{setAuthor(e.target.value);setConsent(false);}}/></label><label className="check-label"><input type="checkbox" checked={includeSource} onChange={e=>{setIncludeSource(e.target.checked);setConsent(false);}}/> Also share my original source code</label><details><summary>Inspect the exact public content</summary><SolutionReplay key={`public-${includeSource}`} artifact={{...job.artifact,source:includeSource?job.artifact.source:undefined}}/></details><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I consent to publish this version under my display name for public viewing. I have the right to share it. Others may copy what I make public; unpublishing cannot recall their copies.</label><p>{includeSource?'Original source will be public.':'Original source remains private.'} No broader reuse license is granted by this viewing consent.</p><button className="generate-button" disabled={!consent||!author.trim()||!config?.publishing||busy} onClick={()=>mutate('publish',{consent,author,includeSource,hash:job.artifact_hash})}>Publish this version <Globe size={16}/></button>{!config?.publishing&&<p>Public sharing is not enabled for this beta yet.</p>}</div>}</section></div>}
    {job&&<div className="delete-run"><button onClick={()=>{setSource(job.source);setProblem(job.problem);setInput(JSON.stringify(job.input));setSelected(null);setJob(null);setMessage('Loaded this exact source into the editor. Change the example or edit the code, then submit a new private revision.');window.scrollTo({top:0,behavior:'smooth'});}}>Edit source or try another example</button>{confirmDelete?<><span>Delete this submission, its story, and its public version?</span><button onClick={()=>mutate('delete')} disabled={busy}>Delete permanently</button><button onClick={()=>setConfirmDelete(false)}>Keep it</button></>:<button onClick={()=>setConfirmDelete(true)}>Delete this submission</button>}</div>}
    <section className="sample-intro"><div><span className="eyebrow">TRY A RECORDED EXAMPLE</span><h2>Same problem. Different journeys.</h2><p>These authored samples show real Python traces. They are not generated from your upload.</p></div><div><button className={sample===0?'active':''} onClick={()=>{setSample(0);setSelected(null);setJob(null);}}><Play size={15}/> Sliding window</button><button className={sample===1?'active':''} onClick={()=>{setSample(1);setSelected(null);setJob(null);}}><Play size={15}/> Nested loops</button></div></section>
    {sample!==null&&<SolutionReplay key={`sample-${sample}`} artifact={sampleArtifact(sample)} sample/>}
  </main></AcademyShell>;
}
